Repository andela/artemis-ah-backend, pull requests merged in 2019-03, with the labels that each got.

#10 #164198488 setup jwt
  package.json
  server/middlewares/AuthenticateUser.js
  server/routes/articles.js
  server/test/auth.spec.js
  server/utils/HelperUtils.js
  utils/HelperUtils.js
Labels: wip

#13 #164198494 create article
  .travis.yml
  package.json
  pull_request_template.md
  server/controllers/article.js
  server/database/migrations/20190227133849-create-article.js
  server/database/models/article.js
  server/routes/articles.js
  server/test/articles.spec.js
  server/test/auth.spec.js
  server/utils/response.js
  server/validations/create-article.js
Labels: enhancement

#18 #164198501 endpoint to get articles
  server/controllers/article.js
  server/controllers/user.js
  server/database/models/article.js
  server/database/models/user.js
  server/routes/articles.js
  server/test/articles.spec.js
  server/utils/response.js
Labels: enhancement

#21 #164345308 set up husky for code linting
  .eslintrc.json
  package.json
  server/config/index.js
  server/config/passport.js
  server/controllers/article.js
  server/controllers/user.js
  server/database/config/config.js
  server/database/migrations/20190227151431-create-user.js
  server/database/models/index.js
  server/routes/articles.js
  server/routes/users.js
  server/test/articles.spec.js
  server/utils/response.js
  utils/HelperUtils.js
Labels: wip

#25 #164198508 create migrations for article comments and article comment likes
  server/database/migrations/20190304180753-create-article-comment.js
  server/database/migrations/20190304180856-create-article-comment-like.js
  server/database/models/article.js
  server/database/models/articlecomment.js
  server/database/models/articlecommentlike.js
  server/database/models/user.js
Labels: enhancement

#28 #164198496 implement comment feature
  .eslintrc.json
  package.json
  server/controllers/articleComment.js
  server/controllers/index.js
  server/database/migrations/20190103185917-create-tag.js
  server/database/migrations/20190304180753-create-article-comment.js
  server/database/migrations/20190304180856-create-article-comment-like.js
  server/routes/articles.js
  server/test/comment.spec.js
  server/test/index.js
Labels: wip

#30 #164198508 feature to toggle like on a comment for an article
  README.md
  server/controllers/article-comment-like.js
  server/routes/articles.js
  server/test/articles.spec.js
  swagger.yaml
Labels: enhancement

#51 #164427956 feature for notification for articles from followed users.
  .eslintrc.json
  package.json
  server/config/index.js
  server/config/passport.js
  server/controllers/article-comment-like.js
  server/controllers/article.js
  server/controllers/articleComment.js
  server/controllers/follow.js
  server/controllers/user.js
  server/database/migrations/20190103185917-create-tag.js
  server/database/migrations/20190227133849-create-article.js
  server/database/migrations/20190227151431-create-user.js
  server/database/migrations/20190302161532-create-follower.js
  server/database/migrations/20190304180753-create-article-comment.js
  server/database/migrations/20190304180856-create-article-comment-like.js
  server/database/migrations/20190305100936-create-rating.js
  server/database/models/article.js
  server/database/models/articlecomment.js
  server/database/models/articlecommentlike.js
  server/database/models/follower.js
  server/database/models/index.js
  server/database/models/rating.js
  server/database/models/tag.js
  server/database/models/user.js
  server/database/models/usernotification.js
  server/database/seeders/20190303192902-add-tags.js
  server/middlewares/AuthenticateArticle.js
  server/middlewares/Trimmer.js
  server/middlewares/ValidateComment.js
  server/middlewares/ValidateUser.js
  server/routes/articles.js
  server/routes/profile.js
  server/test/articles.spec.js
  server/test/comment.spec.js
  server/test/follow.spec.js
  server/test/index.js
  server/test/notification.spec.js
  server/test/profile.spec.js
  server/test/user.spec.js
  server/utils/HelperUtils.js
  server/utils/markups/articleNotificationMarkup.js
  server/utils/markups/emailTemplate.js
  server/utils/markups/emailVerificationMarkup.js
  server/utils/markups/passwordResetMarkup.js
  server/validations/create-article.js
  server/validations/rate-article.js
Labels: enhancement

#58 #164630360 Fix bug for distributing notification
  server/controllers/article.js
  server/utils/HelperUtils.js
  server/utils/markups/articleNotificationMarkup.js
  server/utils/markups/emailTemplate.js
Labels: bug fix

#59 #164608984 add feature to get edit history for a comment
  server/controllers/articleComment.js
  server/routes/articles.js
  server/test/commentEditHistory.spec.js
  server/test/index.js
Labels: enhancement

#63 #164727481 save uploaded article cover url
  .env.sample
  server/controllers/article.js
  server/database/migrations/20190227133849-create-article.js
  server/database/models/article.js
  server/test/articles.spec.js
  server/validations/create-article.js
Labels: enhancement
